language: php
php:
  - '7.1.9'
install:
  - composer install
before_script: echo 'date.timezone = "PRC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - vendor/bin/phpunit --configuration phpunit.xml